// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngupqmwtbncjkegbhys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ3VwcW13dGJuY2prZWdiaHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTUwNTEsImV4cCI6MjA1NjY5MTA1MX0.pziqAse7yC0cFl-8B1LUUpwdZY5xO-wAMDTMrCTHC3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);